In [1]:
import pandas as pd
import numpy as np
import array
import re
import datetime 
import itertools
import scipy
from scipy.stats import skew
import statistics,nltk

In [2]:
l=[1,3,4,2]
l.sort()

In [3]:
print(l)

[1, 2, 3, 4]


In [4]:
s=pd.Series([1,2,3])
s

0    1
1    2
2    3
dtype: int64

In [5]:
s=pd.Series(list(['a','b','c','a']))
s

0    a
1    b
2    c
3    a
dtype: object

In [6]:
s=pd.Series([[3,6,9,1],[1,2]])
s

0    [3, 6, 9, 1]
1          [1, 2]
dtype: object

In [7]:
l1=list('ksfkelsnv')

In [8]:
l1

['k', 's', 'f', 'k', 'e', 'l', 's', 'n', 'v']

In [9]:
s=pd.DataFrame(pd.Series([3,5,9,1],[1,7,3,5])).reset_index(drop=False)

In [10]:
s

index  0
0      1  3
1      7  5
2      3  9
3      5  1

In [11]:
from nltk.tokenize import word_tokenize,sent_tokenize

In [12]:
ex="time to start ml programming and natural processing.Python will make it easy"

In [13]:
from nltk.tag import pos_tag

In [14]:
sent=sent_tokenize(ex)

In [15]:
sent

['time to start ml programming and natural processing.Python will make it easy']

In [16]:
words=word_tokenize(ex)
words

['time',
 'to',
 'start',
 'ml',
 'programming',
 'and',
 'natural',
 'processing.Python',
 'will',
 'make',
 'it',
 'easy']

In [17]:
ps=pos_tag(words)

In [18]:
type(ps)

list

In [19]:
ps

[('time', 'NN'),
 ('to', 'TO'),
 ('start', 'VB'),
 ('ml', 'NN'),
 ('programming', 'NN'),
 ('and', 'CC'),
 ('natural', 'JJ'),
 ('processing.Python', 'NN'),
 ('will', 'MD'),
 ('make', 'VB'),
 ('it', 'PRP'),
 ('easy', 'JJ')]

In [20]:
ps1=[]
for i in ps:
    ps1.append(i[1])

In [21]:
ps1

['NN', 'TO', 'VB', 'NN', 'NN', 'CC', 'JJ', 'NN', 'MD', 'VB', 'PRP', 'JJ']

In [22]:
ex="the big yellow bird flew over the house"

In [23]:
def propress(gh):
    words=nltk.word_tokenize(gh)
    pos_words=nltk.pos_tag(words)
    return pos_words

In [24]:
ex1=propress(ex)
ex1

[('the', 'DT'),
 ('big', 'JJ'),
 ('yellow', 'JJ'),
 ('bird', 'NN'),
 ('flew', 'VBD'),
 ('over', 'IN'),
 ('the', 'DT'),
 ('house', 'NN')]

In [25]:
nltk.help.upenn_tagset('VB')

VB: verb, base form
    ask assemble assess assign assume atone attention avoid bake balkanize
    bank begin behold believe bend benefit bevel beware bless boil bomb
    boost brace break bring broil brush build ...


In [26]:
###Enumerate using List comprehension
list1=[1,2,3,4]

In [27]:
list(enumerate(list1))

[(0, 1), (1, 2), (2, 3), (3, 4)]

In [28]:
for i in enumerate(list1):
    print(i)

(0, 1)
(1, 2)
(2, 3)
(3, 4)


In [29]:
[s for s in enumerate(list1)]

[(0, 1), (1, 2), (2, 3), (3, 4)]

In [30]:
#Removing Duplicates in a list
list1=[1,1,2,4,4,5]
list2=[]

In [31]:
for i in list1:
    if i not in list2:
        list2.append(i)
print(list2)

[1, 2, 4, 5]


In [32]:
#Merging to dictionaries to a list
a={'a1':1,'b':2,'c':3}

In [33]:
b={'d':4,'e':5}

In [34]:
z={**a,**b}
z

{'a1': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5}

In [35]:
a1=list(z.items())
a1

[('a1', 1), ('b', 2), ('c', 3), ('d', 4), ('e', 5)]

In [36]:
a2=[]
for i in a1:
    a2.append(i[1])
print(a2)

[1, 2, 3, 4, 5]


In [37]:
l1=[['adi',1],['sd',2],['fg',5]]

In [38]:
l1[2][0:1]

['fg']

In [39]:
list1=[1,2,3]

In [40]:
help(all)

Help on built-in function all in module builtins:

all(iterable, /)
    Return True if bool(x) is True for all values x in the iterable.
    
    If the iterable is empty, return True.



In [41]:
name=['ru','df','gh','A','B']
marks=[3,5,7,8]

l1=set(itertools.zip_longest(name,marks))
l2=set(zip(name,marks))

In [42]:
l1

{('A', 8), ('B', None), ('df', 5), ('gh', 7), ('ru', 3)}

In [43]:
l2


{('A', 8), ('df', 5), ('gh', 7), ('ru', 3)}

In [44]:
set(l1)

{('A', 8), ('B', None), ('df', 5), ('gh', 7), ('ru', 3)}

In [45]:
list(l1)

[('df', 5), ('ru', 3), ('B', None), ('gh', 7), ('A', 8)]

In [46]:
name,marks=zip(*l1)
##unzipping

In [47]:
name

('df', 'ru', 'B', 'gh', 'A')

In [48]:
marks

(5, 3, None, 7, 8)

In [49]:
set(name)

{'A', 'B', 'df', 'gh', 'ru'}

In [50]:
l2={'a':1,'b':2}

In [51]:
list(l2.items())

[('a', 1), ('b', 2)]

In [52]:
#tuple repetition
t=['python']*3
t=('python',)*3

In [53]:
t

('python', 'python', 'python')

In [54]:
##for loop using tuple

In [55]:
tu=('geeks',)

In [56]:
hu=('f',)

In [57]:
tu+hu

('geeks', 'f')

In [58]:
for i in range(5):
    tu=(tu,)
    print(tu)

(('geeks',),)
((('geeks',),),)
(((('geeks',),),),)
((((('geeks',),),),),)
(((((('geeks',),),),),),)


In [59]:
for i in range(0,5):
    tu=(tu,)
    print(tu)

((((((('geeks',),),),),),),)
(((((((('geeks',),),),),),),),)
((((((((('geeks',),),),),),),),),)
(((((((((('geeks',),),),),),),),),),)
((((((((((('geeks',),),),),),),),),),),)


In [60]:
l1=[1,1,2,4,5]

In [61]:
l2=list(set(l1))

In [62]:
l2

[1, 2, 4, 5]

In [63]:
s1=set()
s2=set()

In [64]:
for i in range(1,6):
    s1.add(i)

In [65]:
for i in range(1,6):
    s1.add(i)

In [66]:
s1

{1, 2, 3, 4, 5}

In [67]:
h1=list(s1)
h1

[1, 2, 3, 4, 5]

In [68]:
for i in range(3,8):
    s2.add(i)

In [69]:
s2

{3, 4, 5, 6, 7}

In [70]:
s3=s1 | s2 
s3

#in union dupliates are eliminated

{1, 2, 3, 4, 5, 6, 7}

In [71]:
s4=s1 & s2
s4

{3, 4, 5}

In [72]:
s3.issuperset(s4)

#means s3 contains the elements of s4

True

In [73]:
s3.issubset(s4)

False

In [74]:
s4.clear()

In [75]:
s4

set()

#### Generator Expresssion

In [76]:
list1=[1,2,34]

In [77]:
l2=(y+1 for y in list1)

In [78]:
list(l2)

[2, 3, 35]

#### Converting List to Dictionary:

In [79]:
l1=[1,2,3,4,5]
l2=[1,'b','c']

In [80]:
l3=l1[::2]
l3

[1, 3, 5]

In [81]:
l4=l1[1::2]
l4

[2, 4]

In [82]:
l5=l4+list('')
l5

[2, 4]

In [83]:
l5=dict(zip(l3,l4))
l5

{1: 2, 3: 4}

#### Creating Nested Dictionary

In [84]:

l1={'a':{'Gender':'male','Income':25000},'b':{'Gender':'female','Income':30000},'c':{'Gender':'Female','Income':40000}}
print(l1['a']['Income'])
print(l1['a'])

25000
{'Gender': 'male', 'Income': 25000}


In [85]:
l2={'gender':'male','Income':2500}
l1['d']=l2
l1

{'a': {'Gender': 'male', 'Income': 25000},
 'b': {'Gender': 'female', 'Income': 30000},
 'c': {'Gender': 'Female', 'Income': 40000},
 'd': {'gender': 'male', 'Income': 2500}}

In [86]:
l2={l:-l for l in range(3)}
l2

{0: 0, 1: -1, 2: -2}

In [87]:
for i in l1:
    print(i,l1[i])

a {'Gender': 'male', 'Income': 25000}
b {'Gender': 'female', 'Income': 30000}
c {'Gender': 'Female', 'Income': 40000}
d {'gender': 'male', 'Income': 2500}


#### practicing functions,lambda,map,filter,reduce.

In [91]:
l1=[1,2,3]
l2=map(lambda x : x**2,l1)
print(type(l2))
print(list(l2))

<class 'map'>
[1, 4, 9]


In [93]:
l1=range(-5,5)
l2=filter(lambda x:x<0,l1)
print(type(l2))
print(list(l2))

<class 'filter'>
[-5, -4, -3, -2, -1]


In [94]:
a=[1,2,3]

In [95]:
s1=map(lambda x:x**x,a)
s1
list(s1)

[1, 4, 27]

In [96]:
s2=map(lambda x:x<3,a)
s2
list(s2)

[True, True, False]

In [97]:
from functools import reduce

In [98]:
l2=[1,2,3,4]
z1=reduce(lambda x,y:x*y ,l2)
z1

24

#### Converting List to array

In [99]:
l1=[1,2,3,4]

In [100]:
l2=np.array(l1)
l2

array([1, 2, 3, 4])

In [101]:
type(l2)

numpy.ndarray

In [102]:
l2[0:2]+l2[1:3]

array([3, 5])

In [104]:
l1=[{'c1':10,'c2':100},{'c1':20,'c2':200},{'c1':30,'c2':300}]
l2=pd.DataFrame(l1)
l2

c1   c2
0  10  100
1  20  200
2  30  300

In [108]:
l3=[]
for i,r in l2.iterrows():
    print(i)
    print(r)
    l3.append((r['c2'], r['c1']))
print(l3)

0
c1     10
c2    100
Name: 0, dtype: int64
1
c1     20
c2    200
Name: 1, dtype: int64
2
c1     30
c2    300
Name: 2, dtype: int64
[(100, 10), (200, 20), (300, 30)]


In [109]:
import sys

In [110]:
sys.version_info

sys.version_info(major=3, minor=7, micro=1, releaselevel='final', serial=0)

In [111]:
sys.version

'3.7.1 (default, Dec 10 2018, 22:54:23) [MSC v.1915 64 bit (AMD64)]'

In [113]:
for i in range(0,8):
    print(i)
    if i==6:
        break

0
1
2
3
4
5
6


In [121]:
# we can use ''' or """ for commenting multiple lines

In [122]:
def double(num):
    '''Function to double the value'''
    return 2*num

In [123]:
print(double.__doc__)
double(2)

Function to double the value


4

In [124]:
multiline_str = """This is a multiline string with more than one line
oienvvvvv d 
code"""

In [125]:
print(multiline_str)

This is a multiline string with more than one line
oienvvvvv d 
code


In [126]:
l=1+2j

In [127]:
print("lsdmgvdk",isinstance(l,complex) )

lsdmgvdk True


In [129]:
l={1,34,5}

In [130]:
set(l)

{1, 5, 34}

In [131]:
print("1**2**3")

1**2**3


In [132]:
print(3>=3)

True


In [133]:
def hedf(*name):
    print("lnlf",name)
    
hedf('jk','ram') 

lnlf ('jk', 'ram')


In [134]:
result = lambda x: x * x
print(result(5))

25


In [135]:
result4=list(map(lambda x :x ,'human'))

In [136]:
result4

['h', 'u', 'm', 'a', 'n']

In [150]:
s1=[y for y in range(1,7) if (y%2)==0]

In [151]:
s1

[2, 4, 6]

#### List Comprehension

In [153]:
s3=["evEn" if i%2==0 else "odd" for i in range(0,6)]
s3

['evEn', 'odd', 'evEn', 'odd', 'evEn', 'odd']

#### Finding the transpose of the matrix

In [156]:
x=np.matrix([[1,2],[2,3],[3,4]])
x.T
#print(type(x))

matrix([[1, 2, 3],
        [2, 3, 4]])

In [157]:
x1=np.array([[1,2],[2,3],[3,4]])

In [158]:
x1

array([[1, 2],
       [2, 3],
       [3, 4]])

In [159]:
for j in x1:
    print(j)

[1 2]
[2 3]
[3 4]


In [160]:
s=[]
for i in range(2):
    s1=[]
    for j in x1:
        s1.append(j[i])
    s.append(s1)     

In [161]:
s

[[1, 2, 3], [2, 3, 4]]

In [162]:
[[r[i] for r in x1 ]for i in range(2)]

[[1, 2, 3], [2, 3, 4]]

In [166]:
import os
os.listdir()
#os.getcwd()
#os.chdir("")

['.ipynb_checkpoints',
 'Assumptions _code_Ex4.ipynb',
 'CorePython_Ex5.ipynb',
 'CorePython_Ex6.ipynb',
 'Hotel_bookings_Ex7.ipynb',
 'Little_things_python_Ex8.ipynb',
 'Practice_Ex11.ipynb',
 'Python_Datastructures_Ex10.ipynb',
 'Python_datavisualisation_Ex9.ipynb',
 'Python_Ex1.ipynb',
 'Python_Manipulations_Ex2.ipynb',
 'Python_Practice_Ex3.ipynb',
 'Spark_practice.ipynb']

In [167]:
def test(x=None):
    if x is None:
        print("no value here")
    else:
        print("value is there")

In [168]:
test()

no value here


In [176]:
def test1(x=-14):
    if x ==-14:
        print("no value here")
    else:
        print(x)
        print("value is there")

In [177]:
test1()

no value here


In [178]:
test1('kjnjv')

kjnjv
value is there


In [253]:
def avg(marks):
    try:
        len(marks)!=0   
        return(sum(marks)/len(marks))
    except ZeroDivisionError :
        print("Marks are not entered")

In [254]:
def avg(marks):
    assert len(marks)!=0 ,"Marks not entered"
    return(sum(marks)/len(marks))

In [255]:
marks=[20,30,40]
print("avg value is", avg(marks))

avg value is 30.0


In [256]:
marks=[]
print("avg of the value",avg(marks))

AssertionError: Marks not entered

In [257]:
def action(name,ge):
    return "{} sings {}".format(name,ge)

In [258]:
action('parrot','song')

'parrot sings song'

In [259]:
def printHello():
    print("Hello")     
a = printHello()

Hello


#### iter and next Methods

In [260]:
x1=[4,5,6,7]

In [261]:
x=iter(x1)

In [262]:
next(x)

4

#### Generator Expression

In [263]:
l1=[1,2,3,4]

In [264]:
a=(x**2 for x in l1)

In [265]:
a

<generator object <genexpr> at 0x000001D032692CF0>

In [266]:
list(a)

[1, 4, 9, 16]

#### try except IndexError#ZeroDivisionError

In [267]:
a=[1,2,3,4]

In [268]:
try:
    print("value is",a[4])
except IndexError:
    print("An error occured")

An error occured


In [269]:
def dividing(x1,x2):
    try:
        c=(x1+x2)/(x1-x2)
    except ZeroDivisionError:
        print('Div  not possible')

In [270]:
dividing(1,1)

Div  not possible


In [278]:
try:   
    raise NameError("nsiuhyb")
except NameError: 
    print("An exception")
    raise
##finally : No matter what is result of the “try” block, block termed “finally” is always executed. Detailed article 

An exception


NameError: nsiuhyb

In [290]:
import keyword
s='and'
if keyword.iskeyword(s):
    print("yes it is a keyword",s)
else:
    print(s,"not a keyword")

yes it is a keyword and


In [291]:
keyword.kwlist

['False',
 'None',
 'True',
 'and',
 'as',
 'assert',
 'async',
 'await',
 'break',
 'class',
 'continue',
 'def',
 'del',
 'elif',
 'else',
 'except',
 'finally',
 'for',
 'from',
 'global',
 'if',
 'import',
 'in',
 'is',
 'lambda',
 'nonlocal',
 'not',
 'or',
 'pass',
 'raise',
 'return',
 'try',
 'while',
 'with',
 'yield']

In [292]:
print("adi");print("soma")

adi
soma


In [293]:
print("adi",end="") 
print("soma")

adisoma


In [294]:
a=[1,2,3,4]

In [295]:
for i in range(4):
    print(a[i],end=' ')

1 2 3 4 

#### Taking multiple i/p's from users

In [296]:
x,y,z=(input("enter three values").split(','))

enter three values1,2,3


In [297]:
y

'2'

In [311]:
x,y,z=['1','2','3']

In [312]:
y=int(y)+int(x)

In [313]:
y

3

In [314]:
x=int(input("enter the value"))


enter the value123


In [315]:
x

123

In [316]:
x,y,z=[int(x) for x in input("Enter the values").split()]

Enter the values1 2 3


In [317]:
x

1

In [318]:
print("Aditya","OFSS",sep="@")

Aditya@OFSS


In [319]:
String2 = "{l} {f} {g}".format(g = 'Geedks', f = 'For', l = 'Life')

In [320]:
String2

'Life For Geedks'

#### Replace 

In [325]:
String="life is 'beutiful' ,life"

In [326]:
String2=String.replace("life","love")

In [327]:
String2

"love is 'beutiful' ,love"

In [328]:
String2=String.upper()

In [329]:
String2

"LIFE IS 'BEUTIFUL' ,LIFE"

In [331]:
#Regular expressions are simple enough, if you know them.
#where \w is alphanumeric
#\s is space
import re
s = "string. With. Punctuation?"
s=re.sub('[^\w\s]',"",s)
s

'string With Punctuation'

In [335]:
import array

In [336]:
import numpy as np

In [337]:
s1=[1,2,3]

In [338]:
s1.append([5,7,9])
s1.extend([5,7,9])
s1

[1, 2, 3, [5, 7, 9], 5, 7, 9]

In [348]:
import array
arr1=np.array([1,4,3])

In [340]:
arr2=np.array([1,2])

In [341]:
arr1

array([1, 4])

In [342]:
arr1[-1]

4

In [344]:
type(arr1)

numpy.ndarray

In [345]:
arr1

array([1, 4])

In [349]:
arr2=np.array([2,3,12])
arr2

array([ 2,  3, 12])

In [350]:
arr3=np.add(arr1,arr2)

In [351]:
arr3

array([ 3,  7, 15])

In [352]:
del arr3

In [353]:
arr4=array.array('d', [1.0, 2.0, 6.0, 4.0, 8.0, 9.0, 1.0, 2.0, 3.0, 12.0])

In [354]:
type(arr4)

array.array

In [355]:
arr4.pop(1) ##it will remove the element at the mentioned index

2.0

In [356]:
arr4

array('d', [1.0, 6.0, 4.0, 8.0, 9.0, 1.0, 2.0, 3.0, 12.0])

##### Packing and Unpacking

In [357]:
l1=[2,3,4]
l2=range(*l1)

In [358]:
l2

range(2, 3, 4)

In [359]:
for i in range(*l1):
    print(i)

2


In [360]:
type((l2))

range

In [361]:
def jukin(a,b,c,d):
    print(a,b,c,d)
    
    
l1=[1,2,3,4]

jukin(*l1)
    

1 2 3 4


In [362]:
def mysum(*args):
    sum=0
    for i in range(0,len(args)):
        sum=sum+args[i]
    return sum 

In [363]:
x=mysum(1,2,3,4)
x

10

In [364]:
l1='a'

l2=ord(l1)
l2

97

In [365]:
l1="geeks"

In [366]:
tuple(l1)

('g', 'e', 'e', 'k', 's')

In [367]:
list(l1)

['g', 'e', 'e', 'k', 's']

In [368]:
set(l1)

{'e', 'g', 'k', 's'}

In [369]:
l1=[("a","b"),("c","d")]

In [370]:
dict(l1)

{'a': 'b', 'c': 'd'}

In [371]:
complex(1,2)

(1+2j)

#### Enoding and Decoding

In [379]:
l1='GeeksforGeeks'

l2=b'GeeksforGeeks'

In [380]:
l2

b'GeeksforGeeks'

In [381]:
l3=l1.encode()

In [382]:
l3

b'GeeksforGeeks'

In [383]:
l3=l1.encode("ascii")

In [384]:
if (l3==l2):
    print("encoding is successfull")
else:
    print("Failure")

encoding is successfull


In [385]:
l3=l2.decode()
l3

'GeeksforGeeks'

In [386]:
if (l3==l1):
    print("Decoding is successfull")
else:
    print("Failure")

Decoding is successfull


In [387]:
#Swapping two variables

x=1
y=2
x,y=y,x

In [388]:
print(x,y)

2 1


In [389]:
l1={"a":1,"b":2}

In [390]:
"b" in l1

True

In [391]:
2 in l1

False

In [392]:
l="Geeks for Geeks"
#x=l.split()
#x=l.split(":")
x=l.split(" ",1)

In [393]:
x

['Geeks', 'for Geeks']

In [394]:
l="cat.5467.adi"
x=l.split()
#x=l.split(":")
#x=l.split(".")[-2]

In [395]:
x

['cat.5467.adi']

In [399]:
#operator overloading
#Here * is like a operator overloading
x=print(1*1)
x

1


In [400]:
z=print("Geek"*4)

GeekGeekGeekGeek


In [401]:
#Generator 
def gentor():
    yield 6
    yield 2
    yield 3    

In [402]:
list(gentor())

[6, 2, 3]

In [403]:
for i in gentor():
    print(i)

6
2
3


In [404]:
def gentor1():
    yield 
    yield 8
    yield 9

In [405]:
x=gentor1()
x



<generator object gentor1 at 0x000001D032754390>

In [406]:
def genr():
    yield 7
    yield 8
    yield 9

In [407]:
z=genr()

In [408]:

next(z)

7

In [409]:
print(next(x))

None


In [413]:
#Iterator
d={}
d['a']=123
d['b']=234
d

{'a': 123, 'b': 234}

In [414]:
for i in d:
    print(d[i])

123
234


In [415]:
##Using Iterators effectively
l1=['Astin','Audi','Merce']

i=0
while(i<len(l1)):
    print(l1[i])
    i=i+1

Astin
Audi
Merce


In [416]:
for i in l1:
    print(i)

Astin
Audi
Merce


In [417]:
for i in range(len(l1)):
    print(l1[i])

Astin
Audi
Merce


In [418]:
list(enumerate(l1))

[(0, 'Astin'), (1, 'Audi'), (2, 'Merce')]

In [435]:
for i in enumerate(l1):
    #print(i[1])
    #print(i)
    print(i[0])

0
1
2
3
4
5
6


In [436]:
l1=['Astin','Audi','Merce']
print(enumerate(l1))


In [437]:
for i in enumerate(l1,start=2):
    print(i)


(2, 'Astin')
(3, 'Audi')
(4, 'Merce')


In [438]:
cars=["austin","Audi","merce"]
acces=["huma","repairtool"]

prices={1:"5400",2:"2000",3:"3000",4:"500",5:"1000"}


#for i,j in enumerate(cars,start=1):
#    print("car:{} price:{} ".format(j,prices[i]))
    
for i,j in enumerate(cars,start=1):
    print("car :%s price %s"%(j,prices[i]))


car :austin price 5400
car :Audi price 2000
car :merce price 3000


In [443]:
cars=["austin","Audi","merce"]
acces=["huma","repairtool","gyun"]


for i,j in zip(cars,acces):
    print(i)
    print(j)
    print((i,j))

austin
huma
('austin', 'huma')
Audi
repairtool
('Audi', 'repairtool')
merce
gyun
('merce', 'gyun')


In [444]:
l,l1 =zip(*[('austin', 'huma'),
('Audi', 'repairtool'),
('merce', 'gyun')])

In [445]:
l

('austin', 'Audi', 'merce')

In [446]:
import itertools
l1=[2,4,5,7,8]
z=itertools.filterfalse(lambda x:x%2==0,l1)

In [447]:
list(z)

[5, 7]

In [448]:
l1[0::2]

[2, 5, 8]

In [449]:
l2=[[1,3,6],[3,6,1],[9,11,12]]

list(itertools.starmap(max,l2))

[6, 6, 12]

In [450]:
l1=[2,4,6,7,8,10,20]

list(itertools.takewhile(lambda x:x%2==0,l1))
#and it is opposite of dropwhile

[2, 4, 6]

In [451]:
it=itertools.tee(iter(l1),4)

In [452]:
print(dict(itertools.zip_longest(['era','ertd'],['adi','soma'])))

{'era': 'adi', 'ertd': 'soma'}


In [453]:
it

(<itertools._tee at 0x1d032763c88>,
 <itertools._tee at 0x1d032764b48>)

In [454]:
for i in range(0,2):
    print(list(it[i]))

[2, 4, 6, 7, 8, 10, 20]
[2, 4, 6, 7, 8, 10, 20]


In [455]:
print(*(itertools.zip_longest("Aditya","srikanth",fillvalue='_')))

('A', 's') ('d', 'r') ('i', 'i') ('t', 'k') ('y', 'a') ('a', 'n') ('_', 't') ('_', 'h')


In [456]:
print(list(itertools.product('AB','12')))

[('A', '1'), ('A', '2'), ('B', '1'), ('B', '2')]


In [457]:
print(list(itertools.permutations('GHJK',2)))

[('G', 'H'), ('G', 'J'), ('G', 'K'), ('H', 'G'), ('H', 'J'), ('H', 'K'), ('J', 'G'), ('J', 'H'), ('J', 'K'), ('K', 'G'), ('K', 'H'), ('K', 'J')]


In [458]:
print(list(itertools.combinations('GHJK',2)))

[('G', 'H'), ('G', 'J'), ('G', 'K'), ('H', 'J'), ('H', 'K'), ('J', 'K')]


In [459]:
print(list(itertools.combinations_with_replacement('GHJK',2)))

[('G', 'G'), ('G', 'H'), ('G', 'J'), ('G', 'K'), ('H', 'H'), ('H', 'J'), ('H', 'K'), ('J', 'J'), ('J', 'K'), ('K', 'K')]


In [461]:
#correct way of defining empty function in python

def fun():
    pass



In [463]:
#write a prog to generate squares from 1 to 100 using yield
def genr():
    i=0;
    while(i<=10):
        yield i*i
        i=i+1

In [471]:
def genx():
    x=1
    while(x<10):
        x=x*x
        yield x
        x=x+1

In [472]:
for i in genx():
    print(i)

1
4
25


In [473]:
for i in genr():
    print(i)

0
1
4
9
16
25
36
49
64
81
100


In [475]:
#finding the prime numbers b/w 200 and 300

upper=300
lower=200
for num in range(lower,upper+1):
    for i in range(2,num):
        if(num%i==0):
            break
    else:
        print(num)

211
223
227
229
233
239
241
251
257
263
269
271
277
281
283
293


In [476]:
from fractions import Fraction
Fraction(1.45)
print(Fraction(11,23))

11/23


In [478]:
#eval()
#struct()
#pprint()
x=1
z=eval('x+1')
z

2

In [479]:
type(z)

int

In [480]:
def areacal(l):
    return (4*l)

def perical(l):
    return (l*1)

property=input("enter function name")

for l in range(0,5):
    if (property == 'areacal(l)'):
        print("area calculated",eval(property))
    elif(property== 'perical(l)'):
        print("peri calculated",eval(property))
    else:
        print("wrong selection")
        break

enter function nameperical
wrong selection


In [22]:
print(eval('squareRoot(9)', {'squareRoot': sqrt, 'pow': pow}))

3.0


In [23]:
a = 5
print(eval('sqrt(a)', {'__builtins__': None}, {'a': a, 'sqrt': sqrt}))

2.23606797749979


In [495]:
#Closures
def print_msg(msg):
    def printer():
        print(msg)
    return printer

In [496]:
x=print_msg("Hi,how are you")
x()
#here we are able to acess the non local variable

Hi,how are you


In [499]:
import logging 
  
def logger(func): 
    def log_func(*args): 
        print(func(*args)) 
    # Necessary for closure to work (returning WITHOUT parenthesis) 
    return log_func               
  
def add(x, y): 
    return x+y 
  
def sub(x, y): 
    return x-y 
  
add_logger = logger(add) 
sub_logger = logger(sub) 
  
add_logger(3, 3) 
add_logger(4, 5) 
  
sub_logger(10, 5) 
sub_logger(20, 10) 

6
9
5
10


In [501]:
#Ex:2
def make_multiplier_of(n):
    def multiplier(x):
        return x*n
    return multiplier

In [502]:
times3=make_multiplier_of("adi")

In [503]:
print(times3(3))

adiadiadi


In [504]:
times5=make_multiplier_of(5)

In [505]:
print(times5(6))

30


In [506]:
print(times3(times5(5)))

adiadiadiadiadiadiadiadiadiadiadiadiadiadiadiadiadiadiadiadiadiadiadiadiadi


In [507]:
#Printing the palindrome string/number.
a='abcba'
b=121

In [508]:
c=list('abcba')

In [509]:
c

['a', 'b', 'c', 'b', 'a']

In [510]:
d=c[::-1]

In [512]:
z=input()
z1=z[::-1]
if (z1==z):
    print("its a palindrome string")
else:
    print("Not a palindrome")
    

aditya
Not a palindrome


In [514]:
#pyramid formation:
for i in range(5,0,-1):
    print("k*"*i)

k*k*k*k*k*
k*k*k*k*
k*k*k*
k*k*
k*


In [516]:
n="K*"
for i in range(7):
    for j in range(i+1):
        print(n,end=" ")
    print()

K* 
K* K* 
K* K* K* 
K* K* K* K* 
K* K* K* K* K* 
K* K* K* K* K* K* 
K* K* K* K* K* K* K* 


In [518]:
for i in range(1,6,2):
    print("*"*i)

*
***
*****


In [521]:
n=1
for i in range(7):
    for j in range(i+1):
        print(n,end=" ")
        n=n+1
    print()

1 
2 3 
4 5 6 
7 8 9 10 
11 12 13 14 15 
16 17 18 19 20 21 
22 23 24 25 26 27 28 


In [522]:
for i in range(7):
    for j in range(i+1):
        n=j+1
        print(n,end=" ")
    print()    

1 
1 2 
1 2 3 
1 2 3 4 
1 2 3 4 5 
1 2 3 4 5 6 
1 2 3 4 5 6 7 


In [525]:
val=65
for i in range(6):
    for j in range(i+1):
        cha=chr(val)
        print(cha,end=" ")
        val=val+1
    print()

A 
B C 
D E F 
G H I J 
K L M N O 
P Q R S T U 


In [526]:
val=65
for i in range(6):
    for j in range(i+1):
        cha=chr(val)
        print(cha,end=" ")
    val=val+1
    print()

A 
B B 
C C C 
D D D D 
E E E E E 
F F F F F F 


In [530]:
z=np.zeros([5,3])
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [543]:
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [544]:
B=np.array([[3,4,5],[2,7,5],[2,3,4]])
B

array([[3, 4, 5],
       [2, 7, 5],
       [2, 3, 4]])

In [554]:
X=[[1,2,3],[1,5,6]]
X

[[1, 2, 3], [1, 5, 6]]

In [555]:
Y=np.array([[3,4],[5,6]])

In [556]:
Y.T

array([[3, 5],
       [4, 6]])

In [557]:
re=np.zeros([3,2])

In [560]:
for i in range(len(X)):
    for j in range(len(re)):
        re[j][i]=X[i][j]

In [561]:
re

array([[1., 1.],
       [2., 5.],
       [3., 6.]])

In [562]:
np.matmul(A,B)

array([[ 13,  27,  27],
       [ 34,  69,  69],
       [ 55, 111, 111]])

In [566]:
a=np.arange(6).reshape([3,2])

In [567]:
np.reshape(a,(2,3))

array([[0, 1, 2],
       [3, 4, 5]])

In [568]:
np.reshape(a,(3,-1))

array([[0, 1],
       [2, 3],
       [4, 5]])

In [569]:
type(a)

numpy.ndarray

In [570]:
a[:2,:1]

array([[0],
       [2]])

In [571]:
a[:2,]

array([[0, 1],
       [2, 3]])

In [577]:
#Median calculation:

a=np.array([1,2,3,4,5,7000,111100000])

In [578]:
#np.percentile(a,50)
np.median(a)

4.0

In [586]:
intab = "aeiou"
outtab = "12345"
trantab = str.maketrans(intab, outtab)

strin = "this is string example....wow!!!"
print (strin.translate(trantab))

th3s 3s str3ng 2x1mpl2....w4w!!!


In [587]:
firstString = "gef"
secondString = "eks"
thirdString = "ge"

string = "geeks"
print("Original string:", string) 
  
translation = string.maketrans(firstString,  
                               secondString) 
  
# Translated String 
print("Translated string:",  
       string.translate(translation))

Original string: geeks
Translated string: ekkks


In [589]:
import random
for i in range(0,7):
    print(random.randint(1,5))

5
5
2
3
4
2
4


In [34]:
print("Hello,Hi")

print("__name__ value",__name__)

Hello,Hi
__name__ value __main__


In [592]:
import sys
sys.getdefaultencoding()

'utf-8'

In [593]:
#Sorting the words in alphabetical order

In [594]:
s1=input("enter the sentence")

enter the sentenceajnfjekw wdc


In [595]:
words=s1.split()
words

['ajnfjekw', 'wdc']

In [596]:
set(words)

{'ajnfjekw', 'wdc'}

In [597]:
import datetime as dt

In [598]:
datetime.datetime.now()

datetime.datetime(2020, 6, 26, 14, 28, 27, 100622)

In [599]:
dt.date.today()

datetime.date(2020, 6, 26)

In [600]:
from datetime import date

In [601]:
s=date(2019,4,13)

In [602]:
print(s)

2019-04-13


In [603]:
date.today()

datetime.date(2020, 6, 26)

In [604]:
#Ternary operation 
x,y=2,6

In [605]:
big=x if x>y else y    

In [606]:
big

6

In [608]:
l1=['d','a','c','b']

In [609]:
l2=[ord(i) for i in l1]

In [610]:
l2

[100, 97, 99, 98]

In [611]:
l2.sort()

In [612]:
l2

[97, 98, 99, 100]

In [613]:
l3=[chr(i) for i in l2]

In [614]:
l3

['a', 'b', 'c', 'd']

In [615]:
l1=dict(zip(('a','b','c'),(1,2,3)))
l1

{'a': 1, 'b': 2, 'c': 3}

In [616]:
l2=range(10)

In [617]:
sorted([l1[i] for i in l1])

[1, 2, 3]

In [625]:
l1=np.array([4,1,6,2,7])

In [626]:
l1=l1.argsort()
l1

array([1, 3, 0, 2, 4], dtype=int64)

In [627]:
l2

range(0, 10)

In [630]:
D = ['A','B','C','D','E','AA','AB']
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [631]:
print(le.fit_transform(D))

[0 3 4 5 6 1 2]


In [675]:
import pandas as pd
train  = pd.DataFrame({'id':[1,2,4],'features':[["A B","B C","C D"],["A C","D B","E F"],["C B","D B","F A"]]})

In [676]:
train

id         features
0   1  [A B, B C, C D]
1   2  [A C, D B, E F]
2   4  [C B, D B, F A]

In [677]:
train["features"]

0    [A B, B C, C D]
1    [A C, D B, E F]
2    [C B, D B, F A]
Name: features, dtype: object

In [678]:
train['features_t'] = train["features"].apply(lambda x: (["_".join(i.split(" ")) for i in x]))

In [679]:
print(train['features_t'])

0    [A_B, B_C, C_D]
1    [A_C, D_B, E_F]
2    [C_B, D_B, F_A]
Name: features_t, dtype: object


In [680]:
df = pd.DataFrame(pd.Series(['ff','gg','hh', 'yy'],[24, 12, 48, 30]).reset_index(drop=False))

In [681]:
df

index   0
0     24  ff
1     12  gg
2     48  hh
3     30  yy

In [682]:
df['index']

0    24
1    12
2    48
3    30
Name: index, dtype: int64

In [683]:
df.loc[:,'index']

0    24
1    12
2    48
3    30
Name: index, dtype: int64

In [684]:
def fun(x):
    x[0] = 5
    return x

In [685]:
g = [10,11,12]

In [686]:
print(fun(g))
g

[5, 11, 12]


[5, 11, 12]

In [687]:
#converting dataframe to Dictionary 
df = pd.DataFrame({'Click_Id':['A','B','C','D','E'],'Count':[100,200,300,400,250]})

In [688]:
df

Click_Id  Count
0        A    100
1        B    200
2        C    300
3        D    400
4        E    250

In [698]:
df.set_index('Click_Id')['Count'].to_dict()

{'A': 200, 'B': 200, 'C': 300, 'D': 400, 'E': 250}

In [699]:
df1=df

In [700]:
#Splitting of the string
s1="cat_dog_sto"

In [701]:
s2=s1.split("_")
s2

['cat', 'dog', 'sto']

In [706]:
np.arange(10,26,5)

array([10, 15, 20, 25])

In [707]:
np.linspace(0,2,100)

array([0.        , 0.02020202, 0.04040404, 0.06060606, 0.08080808,
       0.1010101 , 0.12121212, 0.14141414, 0.16161616, 0.18181818,
       0.2020202 , 0.22222222, 0.24242424, 0.26262626, 0.28282828,
       0.3030303 , 0.32323232, 0.34343434, 0.36363636, 0.38383838,
       0.4040404 , 0.42424242, 0.44444444, 0.46464646, 0.48484848,
       0.50505051, 0.52525253, 0.54545455, 0.56565657, 0.58585859,
       0.60606061, 0.62626263, 0.64646465, 0.66666667, 0.68686869,
       0.70707071, 0.72727273, 0.74747475, 0.76767677, 0.78787879,
       0.80808081, 0.82828283, 0.84848485, 0.86868687, 0.88888889,
       0.90909091, 0.92929293, 0.94949495, 0.96969697, 0.98989899,
       1.01010101, 1.03030303, 1.05050505, 1.07070707, 1.09090909,
       1.11111111, 1.13131313, 1.15151515, 1.17171717, 1.19191919,
       1.21212121, 1.23232323, 1.25252525, 1.27272727, 1.29292929,
       1.31313131, 1.33333333, 1.35353535, 1.37373737, 1.39393939,
       1.41414141, 1.43434343, 1.45454545, 1.47474747, 1.49494

In [708]:
np.full([2,2],7)

array([[7, 7],
       [7, 7]])

In [709]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [710]:
#factorial of a number:
m=int(input("enter the number"))
n=1
for i in range(1,m+1):
    n=n*i
print(n)

enter the number5
120


In [711]:
#Inverse of a matrix:
a=np.array([[2,3],[3,2]])
b=np.matrix([[2,4],[2,5]])
c=np.linalg.inv(b)

In [712]:
c

matrix([[ 2.5, -2. ],
        [-1. ,  1. ]])

In [717]:
#finding the mode without using mode function
l1=[2,3,4,5,5,5]

In [718]:
n=len(l1)
from collections import Counter

In [719]:
data=Counter(l1)

In [720]:
data

Counter({2: 1, 3: 1, 4: 1, 5: 3})

In [728]:
get_data=dict(data)
get_data

{2: 1, 3: 1, 4: 1, 5: 3}

In [732]:
Mode=[k for k,v in get_data.items() if v == max(list(get_data.values()))]
Mode

[5]

In [733]:
get_mode="mode is" + "".join(map(str,Mode))

In [734]:
get_mode

'mode is5'

In [737]:
n=299
for i in range(2,n):
    if n%i==0:
        print("this is not prime")
        break
else:
    print("this is P")

this is not prime


In [738]:
def isaer(n):
    s=0
    while(n>0):
        t=n%10
        s=s+t**3
        n=n//10
    return s

In [739]:
k=isaer(154)

In [740]:
if k==n:
    print("jNDFJ")
else:
    print("NA")
    
    

NA


In [741]:
import math

In [742]:
math.pow(2,4)

16.0

In [15]:
picnic_items = {'apples': 5, 'cups': 2} 
 
'I am bringing {} cups.'.format(picnic_items.get('cups'))

'I am bringing 2 cups.'

In [16]:
x,y=4,3

In [17]:
t=x

In [749]:
x=y

In [750]:
y=t

In [751]:
x

3

In [757]:
def rec(n):
    if n==1:
        return 1
    else:
        return n*rec(n-1)
k=rec(6)
k

720

In [758]:
Y = [[5,8,1,2],
    [6,7,3,0],
    [4,5,9,1]]

In [759]:
len(Y[0])

4

In [761]:
#de="this is the date 31/02,2016"
de="this is the date 13/07/1994"
import re

In [762]:
m=re.findall('\d{2}/\d{2}/\d{4}',de)

In [763]:
print(m)

['13/07/1994']


In [764]:
import re
df="45obocop45 eats baby food. BABY FOOD"

In [765]:
m=re.match('\d{2}',df)
print(m)

<re.Match object; span=(0, 2), match='45'>


In [766]:
m=re.sub('eats','eas',df)

m

'45obocop45 eas baby food. BABY FOOD'

In [9]:
se='Robocop is part man, part machine, all cop.'


In [11]:
m=re.findall('robocop',se,re.IGNORECASE)
m

['Robocop']

In [770]:
gr='Serve the public trust.\nProtect the innocent.\nUphold the law.'

In [772]:
m=re.search('tru*',gr)
print(m)

<re.Match object; span=(17, 20), match='tru'>


In [1]:
l1=['a','e','i','o','u']

In [6]:
for i in l2:
    if i in l1:
        print( i,"it is  vowel")
    else:
        print(i,"it is a conso")

a it is  vowel
d it is a conso
i it is  vowel
t it is a conso
y it is a conso
a it is  vowel


In [801]:
x = pd.DataFrame({
    'x_1': [0, 1, 0, 1, np.nan, 500]},
    index=[0, 1, 4, 5, 6, 7])

In [802]:
x

x_1
0    0.0
1    1.0
4    0.0
5    1.0
6    NaN
7  500.0

In [821]:
x=np.random.normal(0,2,10000000)
skew(x)

0.001263628765347176