In [2]:
import pandas,numpy
from numpy import poly1d

#### Creating a Dictionary

In [10]:
data = {'raw': ['Arizona 1 2014-12-23       3242.0',
                'Iowa 1 2010-02-23       3453.7',
                'Oregon 0 2014-06-20       2123.0',
                'Maryland 0 2014-03-14       1123.6',
                'Florida 1 2013-01-15       2134.0',
                'Georgia 0 2012-07-14       2345.6']}

### Creating a DataFrame

In [11]:
D1=pandas.DataFrame(data)

In [12]:
D1

raw
0   Arizona 1 2014-12-23       3242.0
1      Iowa 1 2010-02-23       3453.7
2    Oregon 0 2014-06-20       2123.0
3  Maryland 0 2014-03-14       1123.6
4   Florida 1 2013-01-15       2134.0
5   Georgia 0 2012-07-14       2345.6

### contains

In [13]:
D1["raw"].str.contains("....-..-..")

0    True
1    True
2    True
3    True
4    True
5    True
Name: raw, dtype: bool

### extract

In [15]:
D1['Date']=D1['raw'].str.extract("(....-..-..)")

In [16]:
D1

raw        Date
0   Arizona 1 2014-12-23       3242.0  2014-12-23
1      Iowa 1 2010-02-23       3453.7  2010-02-23
2    Oregon 0 2014-06-20       2123.0  2014-06-20
3  Maryland 0 2014-03-14       1123.6  2014-03-14
4   Florida 1 2013-01-15       2134.0  2013-01-15
5   Georgia 0 2012-07-14       2345.6  2012-07-14

In [27]:
D1["Female"]=D1['raw'].str.extract("(\d)")

In [28]:
D1['state'] = D1['raw'].str.extract('(\w{0,})')

In [29]:
D1

raw        Date Female     state
0   Arizona 1 2014-12-23       3242.0  2014-12-23      1   Arizona
1      Iowa 1 2010-02-23       3453.7  2010-02-23      1      Iowa
2    Oregon 0 2014-06-20       2123.0  2014-06-20      0    Oregon
3  Maryland 0 2014-03-14       1123.6  2014-03-14      0  Maryland
4   Florida 1 2013-01-15       2134.0  2013-01-15      1   Florida
5   Georgia 0 2012-07-14       2345.6  2012-07-14      0   Georgia

### Creating an Array

In [2]:
import numpy
x1=numpy.array([[1,2,3],[2,4,1],[4,5,5]])


#### argsort:Sorting based on index

In [3]:
x2=numpy.argsort(x1)

In [4]:
x2

array([[0, 1, 2],
       [2, 0, 1],
       [0, 1, 2]], dtype=int64)

#### Diff b/w array and List

In [33]:
x2=x1/3
x2

array([[0.33333333, 0.66666667, 1.        ],
       [0.66666667, 1.33333333, 1.66666667],
       [1.33333333, 1.66666667, 1.66666667]])

In [34]:
X1=[1,2,3]
X2=X1/3

TypeError: unsupported operand type(s) for /: 'list' and 'int'

# creating polynomial array

In [35]:
 p = poly1d([3,4,5])
#ax^2+bx+c is the basic structure

In [36]:
p(1)

12

# Creating Matrix

In [37]:
x1=numpy.matrix([[1,2],[3,4]])
x1

matrix([[1, 2],
        [3, 4]])

## Transpose matrix

In [38]:
numpy.transpose(x1)

matrix([[1, 3],
        [2, 4]])

#### Basic stuff

In [39]:
j=27.5
type(j)

float

In [42]:
l=[11,12,13,'a','b','c']

In [43]:
l[::1]

[11, 12, 13, 'a', 'b', 'c']

In [44]:
l[1:3]

[12, 13]

In [45]:
l[::-1]

['c', 'b', 'a', 13, 12, 11]

In [9]:
"""
This example module shows various types of documentation available for use
with pydoc.  To generate HTML documentation for this module issue the
command:

    pydoc -w foo

"""

class Foo(object):
    """
    Foo encapsulates a name and an age.
    """
    def __init__(self, name, age):
        """
        Construct a new 'Foo' object.

        :param name: The name of foo
        :param age: The ageof foo
        :return: returns nothing
        """
        self.name = name
        self.age = age

def bar(baz):
    """
    Prints baz to the display.
    """
    print(baz)

if __name__ == '__main__':
    f = Foo('John Doe', 42)
    bar("hello world")

hello world


### Combining two DataFrames into one List

In [14]:
Dict={'A':[1,2,3,4],'B':[5,6,7,8],'C':[9,10,11,12]}
Dict2={'A2':[1,2,3,4],'B2':[5,6,7,8],'C2':[9,10,11,12]}

In [15]:
DF=pandas.DataFrame(Dict)
DF2=pandas.DataFrame(Dict2)

In [21]:
DF3=[DF,DF2]
DF3[1].loc[:,['A2']]

A2
0   1
1   2
2   3
3   4

In [3]:
int(44.5)*0.5

22.0

apply function

In [72]:
S=pandas.read_csv("stock.csv")

In [65]:
S.head()

Stock Price
0        50.12
1        54.10
2        54.65
3        52.38
4        52.95

In [66]:
def fun(x):
    return x+3

In [67]:
S=S.apply(fun)


In [68]:
S.head()

Stock Price
0        53.12
1        57.10
2        57.65
3        55.38
4        55.95

In [81]:
def fun(num): 
  
    if num<200: 
        return "Low" 
    elif (num>= 200) and (num<400): 
        return "Normal"
    else: 
        return "High"

In [83]:
new = S["Stock Price"].apply(lambda x : fun(x)) 

In [87]:
new1=S["Stock Price"].apply(fun)

In [86]:
new1.head()

0    Low
1    Low
2    Low
3    Low
4    Low
Name: Stock Price, dtype: object

In [88]:
New2=S["Stock Price"].apply(lambda x : x+3)

In [90]:
New2.head()

0    53.12
1    57.10
2    57.65
3    55.38
4    55.95
Name: Stock Price, dtype: float64

In [110]:
def myfunc(n):
    return lambda a : a + n

mydoubler = myfunc(2)

print(mydoubler)
print(mydoubler(5))

<function myfunc.<locals>.<lambda> at 0x000002073A5D1950>
7


##### Series,Lists,join,Split application

In [97]:
DF1=pandas.DataFrame({'A':["ad lawvfoedv eowf w ","oewnfj wfo qwa qw q ","aoif q q wq qdf ef "],'B':[1,2,3] })

In [98]:
DF1

A  B
0  ad lawvfoedv eowf w   1
1  oewnfj wfo qwa qw q   2
2   aoif q q wq qdf ef   3

In [99]:
X=" ".join(DF1.A)

In [100]:
X

'ad lawvfoedv eowf w  oewnfj wfo qwa qw q  aoif q q wq qdf ef '

In [108]:
X1=X.split()
X1

['ad',
 'lawvfoedv',
 'eowf',
 'w',
 'oewnfj',
 'wfo',
 'qwa',
 'qw',
 'q',
 'aoif',
 'q',
 'q',
 'wq',
 'qdf',
 'ef']

In [107]:
pandas.DataFrame(pandas.Series(X1).value_counts())

0
q          3
oewnfj     1
qw         1
qwa        1
w          1
aoif       1
qdf        1
wfo        1
eowf       1
lawvfoedv  1
ad         1
wq         1
ef         1

In [111]:
z1=['as',2,"4",'dslv lds',5]

In [117]:
Z2=pandas.DataFrame(pandas.Series(z1).value_counts())

In [118]:
Z2

0
5         1
as        1
2         1
dslv lds  1
4         1

In [ ]:
# making data frame from csv file  
data = pd.read_csv("employees.csv") 
# removing null values 
data.dropna(inplace = True)
# extracting greatest 5 
large5 = data.nlargest(5, "Salary") 
# sorting in descending order 
data.sort_values("Salary", ascending = False, inplace = True) 

In [1]:
DF1=pandas.DataFrame({'A':["YES","NO",'2-Significant','3-Standard','Supply Chain Management'],'B':[1,2,3,4,5] })

NameError: name 'pandas' is not defined

In [7]:
DF1

A  B
0                      YES  1
1                       NO  2
2            2-Significant  3
3               3-Standard  4
4  Supply Chain Management  5

In [4]:
DF1=DF1[~DF1['A'].isin(['2-Significant','3-Standard','Supply Chain Management'])]

In [5]:
DF1

A  B
0  YES  1
1   NO  2

In [8]:
DF1=DF1.loc[~DF1['A'].isin(['2-Significant','3-Standard','Supply Chain Management'])]

In [10]:
DF1

A  B
0  YES  1
1   NO  2

In [20]:
list1=["can't use google from inside oracle network"]

In [21]:
str(list1)

'["can\'t use google from inside oracle network"]'

In [23]:
lst=[(0, 1), (1, 1), (2, 1)]

In [25]:
for i,f in lst:
    print([i,f])

[0, 1]
[1, 1]
[2, 1]


In [26]:
i=(["n't",
   'use',
   'googl',
   'insid',
   'oracl',
   'network14',
   'undetermin',
   'cust',
   'abandon'],
  'Cloud-Implementation')

In [28]:
i[1]

'Cloud-Implementation'

In [3]:
import itertools
from itertools import zip_longest

In [4]:
x =[1, 2, 3, 4, 5, 6, 7] 
y =[8, 9, 10] 
z = list(zip_longest(x, y)) 
print(z) 

[(1, 8), (2, 9), (3, 10), (4, None), (5, None), (6, None), (7, None)]


In [ ]:
df = pd.DataFrame({'A': ['bat', 'foo', 'bait'],
                   'B': ['abc', 'bar', 'xyz']})
df.replace('^ba.$', 'new', regex=True)

In [2]:
from tqdm import tqdm
for i in tqdm(range(1000)):
    pass

100%|██████████| 1000/1000 [00:00<00:00, 901806.92it/s]


In [ ]:
LR = 2e-2   #2*10^-2
LR

In [4]:
import os
X1=os.listdir('D:\\Education\\Data Science\\Files\\train')
#X1=os.listdir('train')
#X1[0:5]
X1[:5]

['cat.0.jpg', 'cat.1.jpg', 'cat.10.jpg', 'cat.100.jpg', 'cat.1000.jpg']

In [ ]:
img='cat.13.jpg'
img_num = img.split('.')[-3]
img_num

In [2]:
import logging
log=logging.getLogger("es vdclsd")


In [5]:
l1=log.info("Hello")

In [6]:
l1

In [7]:
import logging
log = logging.getLogger("my-logger")
log.info("Hello, world")

In [8]:
import logging

log = logging.getLogger(__name__)

def do_something():
    log.debug("Doing something!")

In [10]:
s=do_something()

In [11]:
s